### ISSUE TITLE
2.8.4 seems to have breaking changes

### ISSUE THREAD

**Issue by colscott** [motss/nodemod#5]
Hi,
https://github.com/motss/nodemod/commit/1fe9f907253fbce258ad3256ce13423ddbcda1a2 seems to have introduced some breaking changes by refactoring selectedDate to date in calendar.js.
This breaks app-datepicker as app-datepicker depends on nodemod ^2.8.1 so pulls 2.8.4. app-datepicker is calling calendar.js with a selectedDate.

Here's the code in app-datepicker:
```js
const calendarDays = calendar({
	dayFormat,
	fullDateFormat,
	locale,
	disabledDates,
	disabledDays,
	firstDayOfWeek,
	max,
	min,
	showWeekNumber,
	weekNumberType,
	selectedDate: firstDayOfMonth,
});
return { ...calendarDays, key };
```

Here's the code in nodemod 2.8.4 calendar.js:
```
const { date, dayFormat, disabledDates = [], disabledDays = [], firstDayOfWeek = 0, fullDateFormat, locale = 'en-US', max, min, showWeekNumber = false, weekLabel = 'Week', weekNumberType = 'first-4-day-week', } = init || {};
```

**Comment by motss** [comment]
Thanks for reporting this. This has been fixed in 9d85e7d642cd872ee483dc3fc0e0bf6cbdb27171.

**Comment by colscott** [comment]
thank you :-) , I'll check it out.

**Comment by colscott** [comment]
Will app-datepicker be getting tagged and published so we can pull the fix?

**Comment by colscott** [comment]
I see it now. Thanks!
